import Layer.* Utils.* Dataloader.*

% 1. load data
[X,Y] = readData('mnist');
X = batch_imresize(X,[5,5]);
sz = size(X);
X = reshape(X, prod(sz(1:end-1)), sz(end));
Y = gray2onehot(Y, 10);
X = normalize(X,2);

% 2. set training options
traning_option = trainingOptions('Optimizer', 'sgdm',...
    'InitialLearnRate', 1e-2, ...
    'LearnRateDropPeriod', 100, ...
    'MaxEpoch',250, ...
    'BatchSize', 512, ...
    'Verbose', true, ...
    'VerboseFrequency', 20,...,...
    'UseGPU',true,...
    'GradientThreshold', 1);

% 3. initialize network
InputLength  = size(X,1);
OutputLength = size(Y,1);
width = 256;
alpha = 0.2;
Net = {FullyConnectedLayer(InputLength,width),...
    LeakyReluLayer(alpha),...
    FullyConnectedLayer(width,width),...
    LeakyReluLayer(alpha),...
    FullyConnectedLayer(width,width),...
    LeakyReluLayer(alpha),...
    FullyConnectedLayer(width,width),...
    LeakyReluLayer(alpha),...
    FullyConnectedLayer(width,OutputLength),...
    SoftmaxLayer(),...
    CrossEntropyLayer()};

% 4. train network
Net = trainNetwork(Net, X, Y, traning_option);

% 5. test trained network
Y_hat = classify(Net, X);

hfig = figure;
NumSample = size(Y,2);

plot(1:NumSample,onehot2gray(Y),'ro',...
    1:NumSample,Y_hat,'b+');
xlabel('x');ylabel('y');title('prediction');
