import Layer.* Utils.* Dataloader.*

% 1. load data
[X,Y] = readData('iris');
X = normalize(X,2);

% 2. set training options
traning_option = trainingOptions('Optimizer', 'sgdm',...
    'InitialLearnRate', 1e-2, ...
    'LearnRateDropPeriod', 4000, ...
    'MaxEpoch', 10000, ...
    'BatchSize', 128, ...
    'Verbose', true, ...
    'VerboseFrequency', 20,...
    'UseGPU',false,...
    'GradientThreshold', 1);

% 3. initialize network
InputLength  = size(X,1);
OutputLength = size(Y,1);
Net = {FullyConnectedLayer(InputLength,50),...
    LeakyReluLayer(0.2),...
    FullyConnectedLayer(50,OutputLength),...
    SoftmaxLayer(),...
    CrossEntropyLayer()};

% 4. train network
Net = trainNetwork(Net, X, Y, traning_option);

% 5. test trained network
Y_hat = classify(Net, X);

hfig = figure;
NumSample = size(Y,2);

plot(1:NumSample,onehot2gray(Y),'ro',...
    1:NumSample,Y_hat,'b+');
xlabel('x');ylabel('y');title('prediction');
